#!/bin/sh

DEBUG=1

# Redirect output to stderr.
exec 1>&2

staged=$(git diff --name-only --cached | grep -E "(.hpp|.cpp)$")

if [ $DEBUG -eq 1 ]; then
    echo "[debug] Chosen files: " $staged
fi

if [ -z "$staged" ]; then
    echo "[info] No files to format"
    exit 0
fi

echo "[info] Applying 'astyle' formatter"

astyle --style=mozilla $staged

if [ $? -eq 0 ]; then
    echo "[info] Check formatting"
    git add $staged
    exit 1
fi

